version: "3.9"
services:
  postgres:
    image: postgres
    ports: 
      - '5432:5432'
    volumes:
      - defi-assistant-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6.2.5-alpine
    ports: 
      - '6379:6379'
    volumes:
      - defi-assistant-redis:/data

  web:
    build: 
      context: .
      args:
         USER_ID: "${USER_ID:-1000}"
         GROUP_ID: "${GROUP_ID:-1000}"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - ./.irb_history:/root/.irb_history
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: "redis://redis:6379/0"
      REDIS_PROVIDER: "REDIS_URL" # sidekiq config
    links:
      - "postgres:db"
      - redis

  sidekiq:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: bundle exec sidekiq 
    volumes:
      - .:/myapp
    environment:
      REDIS_URL: "redis://redis:6379/0"
      REDIS_PROVIDER: "REDIS_URL" # sidekiq config
    links:
      - "postgres:db"
      - redis
    env_file:
      - .env

volumes:
  defi-assistant-postgres:
  defi-assistant-redis:
