:schedule:
  price_alert:
    cron: '*/5 * * * *'   # every 5 min; can't call too often due to API limit
    class: PriceAlertJob
  momo_listing:
    cron: '*/5 * * * *'   # every 5 min
    class: MomoListingJob
  # momo_box_sale_tx:
  #   cron: '*/5 * * * *'   # every 5 min
  #   class: MomoBoxSaleTxJob
  heroku_db_maintenance:
    cron: '0 0 * * *'   # every day at midnight
    class: MomoBoxSaleTxJob
